package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Segunda-feira, 7 de Fevereiro de 2022 13h30min26s BRST
*/

public interface CalculadoraOperations 
{
  double getSoma (double a, double b);
  double getSubtracao (double a, double b);
  double getMultiplicacao (double a, double b);
  double getDivisao (double a, double b);
} // interface CalculadoraOperations
